// Code generated by '{{GENERATOR}}'. DO NOT EDIT.
// template: {{TEMPLATE}}

package generated

import (
	"{{GRPC_INC}}"
	"github.com/TravelTokenMarketplace/travel-token-messenger-bot/v13/internal/rpc"

	"google.golang.org/grpc"
)

var _ {{GRPC_PACKAGE}}.{{SERVICE}}ServiceServer = (*{{TYPE_PACKAGE}}{{SERVICE}}Server)(nil)

type {{TYPE_PACKAGE}}{{SERVICE}}Server struct {
	reqHandler rpc.RequestHandler
}

func register{{SERVICE}}ServiceV{{VERSION}}Server(grpcServer *grpc.Server, reqHandler rpc.RequestHandler) {
	{{GRPC_PACKAGE}}.Register{{SERVICE}}ServiceServer(grpcServer, &{{TYPE_PACKAGE}}{{SERVICE}}Server{reqHandler})
}
