# This example is made for development purposes - for production see docker-compose.yml



### General

# Lower level logging for local development
developer_mode: true

# Timeout in milliseconds to wait for responses to message sent via Matrix
response_timeout: 10000

# Booking Token contract address. This address will be used for minting, buying of Booking Tokens
booking_token_address: 0x459EEdD4bE13bD7D1Af27DA5DdA6d69407118C83

# Blockchain RPC URL. The public endpoint (e.g. wss://base-sepolia.drpc.org) is subject to rate limiting.
# For production or high-volume usage, users should use their own private endpoints from third-party RPC providers (such as QuickNode, Ankr, Infura, etc.).
chain_rpc_url: wss://base-sepolia.drpc.org



### Bot identity

# Private key of the bot in hex format without the 0x prefix.
# Used for signing transactions on the blockchain, also used to log in into Matrix. This
# address needs to have some funds to pay for transaction fees on-chain.
bot_key: YOUR_PRIVATE_KEY_HEX

# Address of the CM Account that the bot belongs to
cm_account_address: 0xYOUR_CM_ACCOUNT_ADDRESS



### Bot authentication cache

# Cache bot authorization checks on-chain (in seconds)
bot_auth_cache_timeout: 300



### Database
db:
    # Path to database dir.
    path: distributor-bot-db



### Matrix
matrix:
    # Hostname of the Matrix server
    host: messenger.chain4travel.com



### Partner Plugin
partner_plugin:
    # Enable or disable the partner plugin rpc client.
    # It must be enabled if bot's cm account supports at least one service or
    # if partner plugin supports booking token cancellation. 
    enabled: true

    # Partner Plugin hostname and port, should be reachable from this machine.
    # Bot tries to connect to this host and port to relay messages that it receives from
    # the distributors through Matrix Server
    host: localhost:50051

    # TLS configuration
    unencrypted: true

    # Required if partner_plugin_unencrypted is false
    ca_file: ca-cert.pem



### RPC server
rpc_server:
    # Enable or disable RPC server. It must be enabled if bot is expecting to receive RPC requests (e.g. its distributor bot).
    enabled: true
    
    # Listen on this port for incoming RPC requests
    port: 9090

    # TLS configuration
    unencrypted: true

    cert_file: server-cert.pem
    key_file: server-key.pem
