booking_token_address: 0xe55E387F5474a012D1b048155E25ea78C7DBfBBC
bot_auth_cache_timeout: 300
bot_key: b466d215f7bf0bcb3be3fc704c16ac5447008e24c2b17bb6c04994f2da850822
chain_rpc_url: wss://columbus.camino.network/ext/bc/C/ws
cm_account_address: 0xe55E387F5474a012D1b048155E25ea78C7DBfBBC
db:
    path: supplier-bot-db
developer_mode: true
e2e_test_mode: false
matrix:
    host: messenger.chain4travel.com
partner_plugin:
    ca_file: ca-cert.pem
    enabled: true
    host: localhost:50051
    unencrypted: true
record_expiration: true
response_timeout: 10000
rpc_server:
    cert_file: server-cert.pem
    enabled: true
    key_file: server-key.pem
    port: 9090
    unencrypted: true
